# Generated by Django 5.1.4 on 2025-01-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/photos/'),
        ),
    ]
