# Generated by Django 5.1.4 on 2025-01-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_maintenance', '0002_preventivemaintenance_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventivemaintenance',
            old_name='form_uploads',
            new_name='ppm_form',
        ),
    ]
