# Generated by Django 5.1.4 on 2025-01-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_maintenance', '0004_rename_ppm_form_preventivemaintenance_ppm_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preventivemaintenance',
            old_name='PPM_form',
            new_name='PPM_Form',
        ),
    ]
