# Generated by Django 5.1.4 on 2025-01-13 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0004_remove_jobcard_corrective_maintenance_id_and_more'),
        ('preventive_maintenance', '0008_alter_preventivemaintenance_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='job_card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_card.jobcard'),
        ),
    ]
