# Generated by Django 5.1.4 on 2025-01-15 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_maintenance', '0010_remove_preventivemaintenance_job_card_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='completed_by',
            field=models.ManyToManyField(related_name='preventive_maintenance_completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
