# Generated by Django 5.1.5 on 2025-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_assethistory'),
        ('preventive_maintenance', '0011_preventivemaintenance_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivemaintenance',
            name='asset',
        ),
        migrations.AddField(
            model_name='preventivemaintenance',
            name='asset',
            field=models.ManyToManyField(related_name='preventive_maintenances', to='asset.asset'),
        ),
    ]
