# Generated by Django 5.1.5 on 2025-03-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventive_maintenance', '0012_remove_preventivemaintenance_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenance',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
