# Generated by Django 5.1.4 on 2025-01-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='maintenance_type',
            field=models.CharField(choices=[('Preventive', 'Preventive'), ('Corrective', 'Corrective'), ('Not Required', 'Not Required')], default='Not Required', max_length=15),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
