# Generated by Django 5.1.4 on 2025-01-13 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_maintenance', '0001_initial'),
        ('job_card', '0002_jobcard_maintenance_type_jobcard_updated_at'),
        ('preventive_maintenance', '0008_alter_preventivemaintenance_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='corrective_maintenance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corrective_maintenance.correctivemaintenance'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='preventive_maintenance_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preventive_maintenance.preventivemaintenance'),
        ),
    ]
