# Generated by Django 5.1.4 on 2025-01-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0003_jobcard_corrective_maintenance_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='corrective_maintenance_id',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='preventive_maintenance_id',
        ),
    ]
