# Generated by Django 5.1.5 on 2025-01-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0005_jobcard_corrective_maintenance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='acknowledged',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
