# Generated by Django 5.1.5 on 2025-01-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0007_jobcard_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='completed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='time_to_acknowledge',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='time_to_complete',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
    ]
