# Generated by Django 5.1.5 on 2025-01-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0010_scheduledjobcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledJobCard',
        ),
    ]
