# Generated by Django 5.1.5 on 2025-03-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0012_jobcard_due_date_jobcard_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='requires_oem_support',
            field=models.BooleanField(default=False),
        ),
    ]
