# Generated by Django 5.1.5 on 2025-03-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0013_jobcard_requires_oem_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardimage',
            name='message',
        ),
        migrations.AddField(
            model_name='jobcardimage',
            name='job_card',
            field=models.ForeignKey(default=130, on_delete=django.db.models.deletion.CASCADE, related_name='jobcardimage_set', to='job_card.jobcard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcardimage',
            name='image',
            field=models.ImageField(upload_to='job_card_images/'),
        ),
    ]
