# Generated by Django 5.1.5 on 2025-03-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0015_alter_jobcardimage_job_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardimage',
            name='job_card',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='job_card_images/'),
        ),
        migrations.AddField(
            model_name='jobcardimage',
            name='message',
            field=models.ForeignKey(default=130, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='job_card.jobcardmessage'),
        ),
        migrations.AlterField(
            model_name='jobcardimage',
            name='image',
            field=models.ImageField(upload_to='job_card_chat/'),
        ),
    ]
