# Generated by Django 5.1.5 on 2025-03-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_card', '0016_remove_jobcardimage_job_card_jobcard_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status_update_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_card_status_images/'),
        ),
        migrations.AlterField(
            model_name='jobcardimage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='job_card.jobcardmessage'),
        ),
    ]
