# Generated by Django 5.1.4 on 2025-01-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('tag_id', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Spare', 'Spare'), ('In Use', 'In Use')], default='Spare', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets_photos/')),
            ],
        ),
    ]
