# Generated by Django 5.1.4 on 2025-01-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='section',
            field=models.CharField(choices=[('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Surveillance', 'Surveillance'), ('Aviation Networks', 'Aviation Networks'), ('Miscellaneous', 'Miscellaneous')], default='Communication', max_length=50),
        ),
    ]
