# Generated by Django 5.1.4 on 2025-01-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Spare', 'Spare'), ('Under Maintenance', 'Under Maintenance'), ('Unserviceable', 'Unserviceable')], default='Spare', max_length=50),
        ),
    ]
