# Generated by Django 5.1.4 on 2025-01-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='part_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
