# Generated by Django 5.1.4 on 2025-01-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_alter_asset_manufacturer_alter_asset_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
