# Generated by Django 5.1.4 on 2025-01-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='part_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
