# Generated by Django 5.1.4 on 2025-01-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_asset_manufacturer_alter_asset_model_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the rack or position', max_length=100, unique=True)),
            ],
        ),
    ]
