# Generated by Django 5.1.4 on 2025-01-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_asset_position_rack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
    ]
