# Generated by Django 5.1.4 on 2025-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_remove_asset_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
