# Generated by Django 5.1.4 on 2025-01-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_alter_asset_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='section',
            field=models.CharField(choices=[('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Surveillance', 'Surveillance'), ('Aviation Networks', 'Aviation Networks'), ('Miscellaneous', 'Miscellaneous')], default='Surveillance', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
