# Generated by Django 5.1.4 on 2025-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_alter_asset_section_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='corrective_maintenance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='morning_shift_daily_inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='night_shift_daily_inspection_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='preventive_maintenance_required',
            field=models.BooleanField(default=True),
        ),
    ]
