# Generated by Django 5.1.5 on 2025-01-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_asset_corrective_maintenance_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
