# Generated by Django 5.1.5 on 2026-04-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_calibrationhistory_calibrationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='oem_life_span',
            field=models.PositiveIntegerField(default=10, help_text='OEM recommended life span in years'),
        ),
    ]
