# Generated by Django 5.1.5 on 2025-03-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_position_alter_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ate_staff',
            field=models.BooleanField(default=True),
        ),
    ]
