# Generated by Django 5.1.5 on 2025-03-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='can_create_job_cards',
            field=models.BooleanField(default=False, help_text='Allow users with this position to create new job cards.'),
        ),
    ]
