# Generated by Django 5.1.4 on 2025-01-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_dashboarditem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarditem',
            name='description',
        ),
    ]
