# Generated by Django 5.1.5 on 2025-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('section', models.CharField(choices=[('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Surveillance', 'Surveillance'), ('Aviation Networks', 'Aviation Networks'), ('Miscellaneous', 'Miscellaneous')], max_length=50, verbose_name='Section')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC Address')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Network Inventory',
                'ordering': ['name'],
            },
        ),
    ]
