# Generated by Django 5.1.4 on 2025-01-10 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
