# Generated by Django 5.1.4 on 2025-01-14 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_alter_logentry_location_delete_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='initials',
        ),
        migrations.AddField(
            model_name='logentry',
            name='initials',
            field=models.ManyToManyField(related_name='logbook_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
