# Generated by Django 5.1.4 on 2025-01-18 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0018_asset_corrective_maintenance_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.CharField(choices=[('Day', 'Day Shift'), ('Night', 'Night Shift')], max_length=5)),
                ('status', models.CharField(choices=[('Ok', 'Ok'), ('Warning', 'Warning'), ('Alarm', 'Alarm'), ('Done', 'Done'), ('Off', 'Off'), ('Unserviceable', 'Unserviceable')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('inspection_progress', models.FloatField(default=0, help_text='Percentage of completed inspections for the shift', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
    ]
