# Generated by Django 5.1.5 on 2025-01-20 17:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0018_asset_corrective_maintenance_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionIdent',
            fields=[
                ('inspection_ident', models.AutoField(primary_key=True, serialize=False)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('shift', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], max_length=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('inspected_by', models.ManyToManyField(blank=True, related_name='daily_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspection_ident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_inspections', to='daily_inspection.inspectionident')),
            ],
        ),
    ]
