# Generated by Django 5.1.4 on 2025-01-19 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0018_asset_corrective_maintenance_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('OK', 'Ok'), ('WARNING', 'Warning'), ('ALARM', 'Alarm'), ('DONE', 'Done'), ('OFF', 'Off'), ('UNSERVICEABLE', 'Unserviceable')], max_length=20, null=True)),
                ('shift', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night')], max_length=5)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
        ),
    ]
