# Generated by Django 5.1.4 on 2025-01-19 04:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspection',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyinspection',
            name='inspected_by',
            field=models.ManyToManyField(blank=True, related_name='daily_inspections', to=settings.AUTH_USER_MODEL),
        ),
    ]
