# Generated by Django 5.1.4 on 2025-01-19 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspection', '0003_alter_dailyinspection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
