# Generated by Django 5.1.5 on 2025-01-20 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspection', '0004_dailyinspection_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionIdent',
            fields=[
                ('inspection_ident', models.AutoField(primary_key=True, serialize=False)),
                ('initiated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
