# Generated by Django 5.1.5 on 2025-01-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_inspection', '0005_inspectionident'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinspection',
            name='inspection_ident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_inspections', to='daily_inspection.inspectionident'),
        ),
    ]
