# Generated by Django 5.1.5 on 2025-01-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_maintenance', '0004_correctivemaintenance_completed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctivemaintenance',
            name='preventive_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctivemaintenance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correctivemaintenance',
            name='root_cause',
            field=models.TextField(blank=True, null=True),
        ),
    ]
