# Generated by Django 5.1.5 on 2025-03-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrective_maintenance', '0007_remove_correctivemaintenance_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctivemaintenance',
            name='task_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
