# Generated by Django 5.1.5 on 2025-02-22 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Maintenance History',
                'verbose_name_plural': 'Maintenance Histories',
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='spare_parts/maintenance_photos/', verbose_name='Photo')),
                ('maintenance_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spare_parts.maintenancehistory', verbose_name='Maintenance History')),
            ],
            options={
                'verbose_name': 'Maintenance Photo',
                'verbose_name_plural': 'Maintenance Photos',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Serial Number')),
                ('part_number', models.CharField(blank=True, max_length=255, verbose_name='Part Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('tag_id', models.CharField(blank=True, max_length=50, verbose_name='Tag ID')),
                ('section', models.CharField(blank=True, choices=[('Communication', 'Communication'), ('Navigation', 'Navigation'), ('Surveillance', 'Surveillance'), ('Aviation Networks', 'Aviation Networks'), ('Miscellaneous', 'Miscellaneous')], max_length=50, verbose_name='Section')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('shelf_number', models.CharField(blank=True, max_length=50, verbose_name='Shelf Number')),
                ('shelf_level', models.CharField(blank=True, max_length=50, verbose_name='Shelf Level')),
                ('box_number', models.CharField(blank=True, max_length=50, verbose_name='Box Number')),
                ('min_stock_level', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Stock Level')),
                ('pr_number', models.CharField(blank=True, max_length=50, verbose_name='PR Number')),
                ('position_rack', models.CharField(blank=True, max_length=50, verbose_name='Position in Rack')),
                ('status', models.CharField(blank=True, choices=[('Operational', 'Operational'), ('Unserviceable', 'Unserviceable'), ('Under Maintenance', 'Under Maintenance')], max_length=50, verbose_name='Status')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Manufacturer')),
                ('model_number', models.CharField(blank=True, max_length=255, verbose_name='Model Number')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.location', verbose_name='Location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
            },
        ),
        migrations.AddField(
            model_name='maintenancehistory',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_history', to='spare_parts.sparepart', verbose_name='Spare Part'),
        ),
        migrations.CreateModel(
            name='CalibrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('calibration_certificate', models.FileField(blank=True, upload_to='spare_parts/calibration_certificates/', verbose_name='Calibration Certificate')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_history', to='spare_parts.sparepart', verbose_name='Spare Part')),
            ],
            options={
                'verbose_name': 'Calibration History',
                'verbose_name_plural': 'Calibration Histories',
            },
        ),
    ]
