# Generated by Django 5.1.5 on 2025-02-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='installation_date',
        ),
    ]
