# Generated by Django 5.1.5 on 2025-02-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0003_remove_sparepart_position_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='position_rack',
            field=models.CharField(blank=True, max_length=50, verbose_name='Position in Rack'),
        ),
        migrations.CreateModel(
            name='SparePartPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='spare_parts/spare_part_photos/', verbose_name='Photo')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spare_parts.sparepart', verbose_name='Spare Part')),
            ],
            options={
                'verbose_name': 'Spare Part Photo',
                'verbose_name_plural': 'Spare Part Photos',
            },
        ),
    ]
