# Generated by Django 5.1.5 on 2025-02-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spare_parts', '0004_sparepart_installation_date_sparepart_position_rack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='installation_date',
        ),
    ]
